name: fashion_fusion
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  loader_overlay: ^4.0.0
  dio: ^5.4.0
  dartz: ^0.10.1
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter_screenutil: ^5.9.0
  toastification: ^1.2.0
  get_it: ^7.6.7
  shared_preferences: ^2.2.2
  internet_connection_checker: ^1.0.0+1
  phone_form_field: ^9.0.5
  persistent_bottom_nav_bar_v2: ^4.2.8
  flutter_staggered_animations: ^1.1.1

  lottie: ^3.0.0
  mason: ^0.1.0-dev.52
  shimmer: ^3.0.0

  intl: ^0.18.0
  flutter_slidable: ^3.0.1
  flutter_carousel_widget: ^2.2.0
  wechat_assets_picker: ^8.9.0-dev.1
  permission_handler: ^11.3.0
  chips_choice: ^3.0.1
  http: ^1.2.0
  timeago: ^3.6.1
  mongo_dart: ^0.10.0


dependency_overrides: 
  photo_manager: ^3.0.0-dev.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.1


flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/
    - assets/faq_data.json


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
